/**
 * Deterministic converter: ActionPlan → ActionSpec v4
 *
 * This is a lookup table, not a generation step. Each actionKind
 * maps to a full v4 template extracted from our 15 reference specs.
 * The LLM only picks the kind + names the inputs. Everything else
 * is hardcoded from proven, testnet-verified specs.
 */

import { ActionPlan } from "./actionPlan";
import { ActionSpec } from "../actionSpec";
import * as fs from "fs";
import * as path from "path";

const SPECS_DIR = path.join(__dirname, "..", "specs");

/**
 * Load a reference spec and customize it with plan details.
 * The reference spec provides the exact sdkMethods, errorMap,
 * successData, etc. — all testnet-proven. The plan only overrides
 * identity fields (name, description, similes).
 */
export function planToSpec(plan: ActionPlan): ActionSpec {
  // Load the reference spec for this action kind
  const refPath = path.join(SPECS_DIR, `${plan.actionKind}.spec.json`);

  if (!fs.existsSync(refPath)) {
    throw new Error(`No reference spec for actionKind: ${plan.actionKind}`);
  }

  const ref: ActionSpec = JSON.parse(fs.readFileSync(refPath, "utf-8"));

  // The reference spec is the source of truth for everything structural:
  // - sdkMethods (the builder recipe)
  // - hedera (service, sdkClass, imports, keys)
  // - successData (receipt/query field extraction)
  // - errorMap (known Hedera errors)
  // - preflightChecks
  // - computedFields
  // - risk, costTier, requiresConfirmation, hasSimulation, irreversible
  //
  // The plan only provides:
  // - A human-readable label/description
  // - Optional input customization (names, descriptions, defaults)
  // - Notes

  // Build the spec — reference + plan overrides
  const spec: ActionSpec = {
    ...ref,
    // Keep the reference name (uppercase snake_case) — it maps to the SDK pattern
    name: ref.name,
    description: plan.description || ref.description,
    // Add plan label as first simile if not already present
    similes: [
      plan.label.toLowerCase(),
      ...ref.similes.filter(s => s.toLowerCase() !== plan.label.toLowerCase()),
    ],
  };

  // If plan specifies input overrides, apply descriptions/defaults
  // but preserve the reference spec's structural fields (type, constraints, etc.)
  if (plan.inputs.length > 0) {
    spec.inputs = ref.inputs.map(refInput => {
      const planInput = plan.inputs.find(p => p.name === refInput.name);
      if (planInput) {
        return {
          ...refInput,
          describe: planInput.description || refInput.describe,
          default: planInput.defaultValue ?? refInput.default,
        };
      }
      return refInput;
    });
  }

  // Add generation metadata to implicitBehaviors
  spec.implicitBehaviors = [
    ...(ref.implicitBehaviors || []),
    {
      behavior: "Generated by Forge Architect",
      details: `From plan: "${plan.label}" at ${new Date().toISOString()}. Notes: ${plan.notes || "none"}`,
    },
  ];

  return spec;
}
